config/routes.rb
Rails.application.routes.draw do
  resources :people
  resources :cars
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'welcome#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/car.rb
class Car < ApplicationRecord
  has_many :ownerships
  has_many :people, through: :ownerships, :dependent => :destroy
end

app/models/ownership.rb
class Ownership < ApplicationRecord
  belongs_to :car
  belongs_to :person
end

app/models/person.rb
class Person < ApplicationRecord
  has_many :ownerships
  has_many :cars, through: :ownerships, :dependent => :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include HttpAuthConcern
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  helper_method :sort_column, :sort_direction
  before_action :set_car, only: [:show, :edit, :update, :destroy]
  before_action :set_person, only: [:new, :create]

  # GET /cars
  # GET /cars.json
  def index
    @cars = Car.order(sort_column + " " + sort_direction)
  end

  # GET /cars/1
  # GET /cars/1.json
  def show
  end

  # GET /cars/new
  def new
    @car = Car.new
  end

  # GET /cars/1/edit
  def edit
  end

  # POST /cars
  # POST /cars.json
  def create
    @car = Car.new(car_params)

    respond_to do |format|
      if @car.save
        if @person
          @car.people << @person
          format.html { redirect_to @person, notice: "#{@person.name} got a new car!" }
          format.json { render :show, status: :created, location: @person }
        else
          format.html { redirect_to @car, notice: 'Car created!' }
          format.json { render :show, status: :created, location: @car }
        end
      else
        format.html { render :new }
        format.json { render json: @car.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cars/1
  # PATCH/PUT /cars/1.json
  def update
    respond_to do |format|
      if @car.update(car_params)
        format.html { redirect_to @car, notice: 'Car updated!' }
        format.json { render :show, status: :ok, location: @car }
      else
        format.html { render :edit }
        format.json { render json: @car.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cars/1
  # DELETE /cars/1.json
  def destroy
    @car.destroy
    respond_to do |format|
      format.html { redirect_to cars_url, notice: 'Car deleted!' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_car
      @car = Car.find(params[:id])
    end

    def set_person
      @person = Person.where(id: params['person']).first
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def car_params
      params.require(:car).permit(:model, :make, :color, :mileage, :is_for_sale)
    end

    def sort_direction
      # set default sort to ascending. 
      # Otherwise set it to the direction param if it is either asc or desc
      %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
    end

    def sort_column
      # sort by model by default.
      Car.column_names.include?(params[:sort]) ? params[:sort] : "model"
    end
end

app/controllers/concerns/http_auth_concern.rb
module HttpAuthConcern
  extend ActiveSupport::Concern

  included do
    before_action :basic_auth
  end

  def basic_auth
    return true if Rails.env.test?
    authenticate_or_request_with_http_basic do |username, password|
      username == 'cars' && password == 'thrive'
    end
  end
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  helper_method :sort_column, :sort_direction
  before_action :set_person, only: [:show, :edit, :update, :destroy]
  before_action :set_car, only: [:new, :create]

  # GET /people
  # GET /people.json
  def index
    @people = Person.order(sort_column + " " + sort_direction)
  end

  # GET /people/1
  # GET /people/1.json
  def show
  end

  # GET /people/new
  def new
    @person = Person.new
  end

  # GET /people/1/edit
  def edit
  end

  # POST /people
  # POST /people.json
  def create
    @person = Person.new(person_params)

    respond_to do |format|
      if @person.save
        if @car
          @person.cars << @car
          format.html { redirect_to @car, notice: 'Owner was successfully created.' }
          format.json { render :show, status: :created, location: @car }
        else
          format.html { redirect_to @person, notice: 'Person was successfully created.' }
          format.json { render :show, status: :created, location: @person }
        end
      else
        format.html { render :new }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /people/1
  # PATCH/PUT /people/1.json
  def update
    respond_to do |format|
      if @person.update(person_params)
        format.html { redirect_to @person, notice: 'Person was successfully updated.' }
        format.json { render :show, status: :ok, location: @person }
      else
        format.html { render :edit }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /people/1
  # DELETE /people/1.json
  def destroy
    @person.destroy
    respond_to do |format|
      format.html { redirect_to people_url, notice: 'Person was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_person
      @person = Person.find(params[:id])
    end

    def set_car
      @car = Car.where(id: params['car']).first
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def person_params
      params.require(:person).permit(:name, :email, :phone_number)
    end

    def sort_direction
      # set default sort to ascending. 
      # Otherwise set it to the direction param if it is either asc or desc
      %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
    end

    def sort_column
      # sort by name by default.
      Person.column_names.include?(params[:sort]) ? params[:sort] : "name"
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
  def sortable(column)
    title = column.titleize
    @direction = column == sort_column && sort_direction == "asc" ? "desc" : "asc"
    link_to title, {:sort => column, :direction => @direction}
  end

  def sort_icon(column)
    icon = sort_direction == "asc" ? material_icon.arrow_upward : material_icon.arrow_downward
    return icon if column == sort_column
  end
end

app/helpers/cars_helper.rb
module CarsHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/cars/_form.html.erb
<%= form_with(model: car, local: true) do |form| %>

  <% if @person %>
    <%= hidden_field_tag 'person', @person.id %>
  <% end %>


  <% if car.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(car.errors.count, "error") %> prohibited this car from being saved:</h2>

      <ul>
      <% car.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= form.label :model %>
    <%= form.text_field :model, class: 'form-control' %>
  </div>

  <div class="field form-group">
    <%= form.label :make %>
    <%= form.text_field :make, class: 'form-control' %>
  </div>

  <div class="field form-group">
    <%= form.label :color %>
    <%= form.text_field :color, class: 'form-control' %>
  </div>

  <div class="field form-group">
    <%= form.label :mileage %>
    <%= form.text_field :mileage, class: 'form-control', type: 'number' %>
  </div>

  <div class="form-check p-5">
    <label for="is_for_sale" class="form-check-label mr-3">
      For sale?
    </label>
    <%= form.check_box :is_for_sale, class: 'form-check-input' %>
  </div>

  <div class="actions">
    <%= form.submit 'Save', :class => 'btn btn-primary' %>
  </div>
<% end %>

app/views/cars/edit.html.erb
<header class="masthead">
  <div class="container d-flex h-100 align-items-center">
    <div class="mx-auto text-center">
      <h1 class="mx-auto my-0 p-5">Editing Car</h1>

      <div class="mx-auto p-5">
        <%= render 'form', car: @car %>
      </div>

      <%= link_to 'Show', @car, :class => "btn btn-primary js-scroll-trigger" %>
      <%= link_to 'Back', cars_path, :class => "btn btn-primary js-scroll-trigger" %>
      <%= link_to 'Add New Owner', new_person_path(:car => @car), :class => "btn btn-primary js-scroll-trigger" %>
    </div>
  </div>
</header>

app/views/cars/index.html.erb
<!-- Header -->
<header class="masthead">
  <div class="mx-auto text-center p-5">
    <p id="notice" class="text-white"><%= notice %></p>
  </div>
  <div class="container d-flex flex-row h-100 align-items-center">
    <div class="p2 col=6">
      <div class="mx-auto text-center">
        <h1 class="mx-auto my-0 p-5">Cars</h1>
        <%= link_to 'New Car', new_car_path, :class => "btn btn-primary js-scroll-trigger" %>
      </div>
    </div>
    <div class="p2 col=10">
      <table class="table table-dark">
        <thead>
          <tr>
            <th scope="col"><%= sortable "model" %><%= sort_icon "model" %></th>
            <th scope="col"><%= sortable "make" %><%= sort_icon "make" %></th>
            <th scope="col"><%= sortable "color" %><%= sort_icon "color" %></th>
            <th scope="col"><%= sortable "mileage" %><%= sort_icon "mileage" %></th>
            <th scope="col"><%= sortable "is_for_sale" %><%= sort_icon "is_for_sale" %></th>
            <th scope="col"><%= sortable "created_at" %><%= sort_icon "created_at" %></th>
          </tr>
        </thead>
        <tbody>
          <% @cars.each do |car| %>
            <tr>
              <td><%= car.model %></td>
              <td><%= car.make %></td>
              <td><%= car.color %></td>
              <td><%= car.mileage %></td>
              <% if car.is_for_sale %>
                <td><%= material_icon.check %></td>
              <% else %>
                <td><%= material_icon.close %></td>
              <% end %>
              <td class="col-2"><%= car.created_at.strftime("%m-%d-%Y")%></td>
              <td><%= link_to 'Details', car %></td>
              <td><%= link_to 'Edit', edit_car_path(car) %></td>
              <td><%= link_to 'Delete', car, method: :delete, data: { confirm: 'Are you sure?' } %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</header>

app/views/cars/new.html.erb
<header class="masthead">
  <div class="container d-flex h-100 align-items-center">
    <div class="mx-auto text-center">
      <h1 class="mx-auto my-0 p-5">New Car</h1>

      <div class="mx-auto p-5">
        <%= render 'form', car: @car %>
      </div>

      <%= link_to 'Back', cars_path %>
    </div>
  </div>
</header>

app/views/cars/show.html.erb
<header class="masthead">
  <div class="mx-auto text-center p-5">
    <p id="notice" class="text-white"><%= notice %></p>
  </div>

  <div class="container d-flex h-50 align-items-center">


    <div class="mx-auto text-center">
      <h1 class="mx-auto my-0 p-5">Car Details</h1>
    </div>

    <table class="table table-dark">
      <thead>
        <tr>
          <th scope="col">Model</th>
          <th scope="col">Make</th>
          <th scope="col">Color</th>
          <th scope="col">Mileage</th>
          <th scope="col">For sale?</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <tr>
          <td><%= @car.model %></td>
          <td><%= @car.make %></td>
          <td><%= @car.color %></td>
          <td><%= @car.mileage %></td>
          <% if @car.is_for_sale %>
            <td><span class="glyphicon glyphicon-ok"></span></td>
          <% else %>
            <td><span class="glyphicon glyphicon-remove"></span></td>
          <% end %>
          <td><%= link_to 'Edit', edit_car_path(@car) %></td>
          <td><%= link_to 'Delete', @car, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      </tbody>
    </table>
  </div>


  <% if @car.people.count > 0 %>
    <div class="container d-flex h-30 align-items-center">
      <div class="mx-auto text-center">
        <h1 class="mx-auto my-0 p-5">Ownership History</h1>
        <%= link_to 'Add New Owner', new_person_path(:car => @car), :class => "btn btn-primary js-scroll-trigger"  %>
      </div>

      <table class="table table-dark">
        <thead>
          <tr>
            <th scope="col">Model</th>
            <th scope="col">Make</th>
            <th scope="col">Color</th>
            <th scope="col">Mileage</th>
            <th scope="col">For sale?</th>
            <th colspan="3"></th>
          </tr>
        </thead>

        <tbody>
          <% @car.people.each do |person| %>
            <tr>
              <td><%= person.name %></td>
              <td><%= person.email %></td>
              <td><%= person.phone_number %></td>
              <td><%= link_to 'Details', person %></td>
              <td><%= link_to 'Edit', edit_person_path(person) %></td>
              <td><%= link_to 'Delete', person, method: :delete, data: { confirm: 'Are you sure?' } %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  <% else %>
    <div class="container d-flex h-30 align-items-center">
      <div class="mx-auto text-center">
        <h1 class="mx-auto my-0 p-5">No Owners Yet... New Car!</h1>
        <%= link_to 'Add New Owner', new_person_path(:car => @car), :class => "btn btn-primary js-scroll-trigger"  %>
      </div>
    </div>
  <% end %>

</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cartrek</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>

  </head>

    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-light fixed-top" id="mainNav">
      <div class="container">
        <a class="navbar-brand js-scroll-trigger" href="/">Home</a>
          <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            Menu
            <i class="fas fa-bars"></i>
          </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item">
              <a class="nav-link js-scroll-trigger" href="/cars">Cars</a>
            </li>
            <li class="nav-item">
              <a class="nav-link js-scroll-trigger" href="/people">Owners</a>
            </li>
          </ul>
        </div>
      </div>
    </nav>


  <body>
    <%= yield %>
  </body>

  <!-- Footer -->
  <footer class="bg-black small text-center text-white-50">
    <div class="container">
      By Diane Douglas 2019
    </div>
  </footer>
  <%= javascript_include_tag 'application' %>
</html>

app/views/people/_form.html.erb
<%= form_with(model: person, local: true) do |form| %>
  <% if @car %>
    <%= hidden_field_tag 'car', @car.id %>
  <% end %>

  <% if person.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(person.errors.count, "error") %> prohibited this person from being saved:</h2>

      <ul>
      <% person.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= form.label :name %>
    <%= form.text_field :name, class: 'form-control' %>
  </div>

  <div class="field form-group">
    <%= form.label :email %>
    <%= form.text_field :email, class: 'form-control' %>
  </div>

  <div class="field form-group">
    <%= form.label :phone_number %>
    <%= form.text_field :phone_number, class: 'form-control' %>
  </div>

  <div class="actions">
    <%= form.submit 'Save', :class => 'btn btn-primary' %>
  </div>
<% end %>

app/views/people/edit.html.erb
<header class="masthead">
  <div class="container d-flex h-100 align-items-center">
    <div class="mx-auto text-center">
      <h1 class="mx-auto my-0 p-5">Editing Person</h1>

      <div class="mx-auto p-5">
        <%= render 'form', person: @person %>
      </div>

      <%= link_to 'Show', @person, :class => "btn btn-primary js-scroll-trigger"  %>
      <%= link_to 'Back', people_path, :class => "btn btn-primary js-scroll-trigger"  %>
      <%= link_to 'Add New Car', new_car_path(:person => @person), :class => "btn btn-primary js-scroll-trigger" %>
    </div>
  </div>
</header>

app/views/people/index.html.erb
<header class="masthead">
  <div class="mx-auto text-center p-5">
    <p id="notice" class="text-white"><%= notice %></p>
  </div>
  <div class="container d-flex h-100 align-items-center">
    <div class="p2 col-6">
      <div class="mx-auto text-center">
        <h1 class="mx-auto my-0 p-5">People</h1>
        <%= link_to 'New Owner', new_person_path, :class => "btn btn-primary js-scroll-trigger" %>
      </div>
    </div>
    <div class="p2 col-10">
      <table class="table table-dark">
        <thead>
          <tr>
            <th scope="col"><%= sortable "name" %><%= sort_icon "name" %></th>
            <th scope="col"><%= sortable "email" %><%= sort_icon "email" %></th>
            <th scope="col">Phone</th>
          </tr>
        </thead>
        <tbody>
          <% @people.each do |person| %>
            <tr>
              <td><%= person.name %></td>
              <td><%= person.email %></td>
              <td><%= person.phone_number %></td>
              <td><%= link_to 'Details', person %></td>
              <td><%= link_to 'Edit', edit_person_path(person) %></td>
              <td><%= link_to 'Delete', person, method: :delete, data: { confirm: 'Are you sure?' } %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</header>

app/views/people/new.html.erb
<header class="masthead">
  <div class="container d-flex h-100 align-items-center">
    <div class="mx-auto text-center">
      <h1 class="mx-auto my-0 p-5">New Owner</h1>

      <div class="mx-auto p-5">
        <%= render 'form', person: @person %>
      </div>

      <%= link_to 'Back', people_path %>
    </div>
  </div>
</header>

app/views/people/show.html.erb
<header class="masthead">
  <div class="mx-auto text-center p-5">
    <p id="notice" class="text-white"><%= notice %></p>
  </div>
  <div class="container d-flex h-50 align-items-center">


    <div class="mx-auto text-center">
      <h1 class="mx-auto my-0 p-5">Personal Details</h1>
    </div>

    <table class="table table-dark">
      <thead>
        <tr>
          <th scope="col">Name</th>
          <th scope="col">Email</th>
          <th scope="col">Phone number</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <tr>
          <td><%= @person.name %></td>
          <td><%= @person.email %></td>
          <td><%= @person.phone_number %></td>
          <td><%= link_to 'Edit', edit_person_path(@person) %></td>
          <td><%= link_to 'Delete', @person, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      </tbody>
    </table>
  </div>

  <% if @person.cars.count > 0 %>
    <div class="container d-flex h-30 align-items-center">
      <div class="mx-auto text-center">
        <h1 class="mx-auto my-0 p-5">Ownership History</h1>
        <%= link_to 'Add New Car', new_car_path(:person => @person), :class => "btn btn-primary js-scroll-trigger"  %>
      </div>

      <table class="table table-dark">
        <thead>
          <tr>
            <th scope="col">Model</th>
            <th scope="col">Make</th>
            <th scope="col">Color</th>
            <th scope="col">Mileage</th>
            <th scope="col">For sale?</th>
            <th colspan="3"></th>
          </tr>
        </thead>

        <tbody>
          <% @person.cars.each do |car| %>
            <tr>
              <td><%= car.model %></td>
              <td><%= car.make %></td>
              <td><%= car.color %></td>
              <td><%= car.mileage %></td>
              <% if car.is_for_sale %>
                <td><span class="glyphicon glyphicon-ok"></span></td>
              <% else %>
                <td><span class="glyphicon glyphicon-remove"></span></td>
              <% end %>
              <td><%= link_to 'Details', car %></td>
              <td><%= link_to 'Edit', edit_car_path(car) %></td>
              <td><%= link_to 'Delete', car, method: :delete, data: { confirm: 'Are you sure?' } %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  <% else %>
    <div class="container d-flex h-30 align-items-center">
      <div class="mx-auto text-center">
        <h1 class="mx-auto my-0 p-5">No Cars Owned Yet!</h1>
        <%= link_to 'Add New Car', new_car_path(:person => @person), :class => "btn btn-primary js-scroll-trigger"  %>
      </div>
    </div>
  <% end %>

</header>

app/views/welcome/index.html.erb
<!-- Header -->
<header class="masthead">
  <div class="container d-flex h-100 align-items-center">
    <div class="mx-auto text-center">
      <h1 class="mx-auto my-0 text-uppercase">Car Trek</h1>
      <h2 class="text-white-50 mx-auto mt-2 mb-5">A Rails app for keeping track of Cars and their Owners.</h2>
      <a href="cars/new" class="btn btn-primary js-scroll-trigger">New Car</a>
      <a href="people/new" class="btn btn-primary js-scroll-trigger">New Owner</a>
    </div>
  </div>
</header>